/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.exemple.views;

import AppPackage.AnimationClass;

/**
 *
 * @author hp
 */
public class ChaoJDialog extends javax.swing.JDialog {

    /**
     * Creates new form ChaoJDialog
     */
    public ChaoJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }

    public void init(){
        setLocationRelativeTo(this);
        AnimationClass anim = new AnimationClass();
        anim.jLabelXLeft(lbldo.getX(),-1000 ,3, 1, lbldo);
        anim.jLabelXRight(lblvang.getX(),1000 ,3, 1, lblvang);
        anim.jLabelYDown(lblxanhchuoi.getY(),1000 ,3, 1, lblxanhchuoi);
        anim.jLabelYDown(lblxanhbien.getY(),1000 ,5, 1, lblxanhbien);
        anim.jLabelXRight(-500, 10, 1, HEIGHT, lblWellCome);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblvang = new javax.swing.JLabel();
        lblxanhbien = new javax.swing.JLabel();
        lblxanhchuoi = new javax.swing.JLabel();
        lbldo = new javax.swing.JLabel();
        lblWellCome = new javax.swing.JLabel();
        lblanh = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblvang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/exemple/icon/Path 1.png"))); // NOI18N
        lblvang.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(lblvang, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 440, -1));

        lblxanhbien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/exemple/icon/Path 3.png"))); // NOI18N
        lblxanhbien.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(lblxanhbien, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 460, 360));

        lblxanhchuoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/exemple/icon/Path 4.png"))); // NOI18N
        lblxanhchuoi.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(lblxanhchuoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 530, 360));

        lbldo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/exemple/icon/Path 2.png"))); // NOI18N
        jPanel2.add(lbldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, -1));

        lblWellCome.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblWellCome.setForeground(new java.awt.Color(102, 102, 102));
        lblWellCome.setText("welcome to hotel");
        jPanel2.add(lblWellCome, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, -1, -1));

        lblanh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/exemple/icon/khachsan.png"))); // NOI18N
        jPanel2.add(lblanh, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 320, 340));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 410));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChaoJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChaoJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChaoJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChaoJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ChaoJDialog dialog = new ChaoJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblWellCome;
    private javax.swing.JLabel lblanh;
    private javax.swing.JLabel lbldo;
    private javax.swing.JLabel lblvang;
    private javax.swing.JLabel lblxanhbien;
    private javax.swing.JLabel lblxanhchuoi;
    // End of variables declaration//GEN-END:variables
}
