/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.exemple.views;

import com.exemple.controller.SoDoPhongDAO;
import com.exemple.entity.DanhMucSoDoPhong;
import com.exemple.entity.SoDoPhong;
import java.awt.Panel;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Minh Triet
 */
public class SoDoPhongJPanel extends javax.swing.JPanel {

    List<DanhMucSoDoPhong> listDanhMucSoDoPhong = new ArrayList<>();
    List<SoDoPhong> listDataDanhMucSoDoPhong = new ArrayList<>();

    public SoDoPhongJPanel() {
        initComponents();
        init();
    }

    private void init() {
        SoDoPhongDAO sdpDAO = new SoDoPhongDAO();
        listDataDanhMucSoDoPhong = sdpDAO.selectSoDoPhong();
        addToListDanhMucSoDoPhong();
        sdpDAO.setInformationSoDoPhong(listDanhMucSoDoPhong, listDataDanhMucSoDoPhong);
        for (DanhMucSoDoPhong item : listDanhMucSoDoPhong) {
            SoDoPhongDAO spDAOchange = new SoDoPhongDAO(item.getPanel());
            spDAOchange.setEvent(listDanhMucSoDoPhong);
        }
    }

    private void addToListDanhMucSoDoPhong() {
        listDanhMucSoDoPhong.add(new DanhMucSoDoPhong("T1P1", panelT1P1, lblT1P1, lblLoaiT1P1, lblTrangThaiT1P1));
        listDanhMucSoDoPhong.add(new DanhMucSoDoPhong("T1P2", panelT1P2, lblT1P2, lblLoaiT1P2, lblTrangThaiT1P2));
        listDanhMucSoDoPhong.add(new DanhMucSoDoPhong("T1P3", panelT1P3, lblT1P3, lblLoaiT1P3, lblTrangThaiT1P3));
        listDanhMucSoDoPhong.add(new DanhMucSoDoPhong("T1P4", panelT1P4, lblT1P4, lblLoaiT1P4, lblTrangThaiT1P4));
        listDanhMucSoDoPhong.add(new DanhMucSoDoPhong("T1P5", panelT1P5, lblT1P5, lblLoaiT1P5, lblTrangThaiT1P5));
        listDanhMucSoDoPhong.add(new DanhMucSoDoPhong("T2P1", panelT2P1, lblT2P1, lblLoaiT2P1, lblTrangThaiT2P1));
        listDanhMucSoDoPhong.add(new DanhMucSoDoPhong("T2P2", panelT2P2, lblT2P2, lblLoaiT2P2, lblTrangThaiT2P2));
        listDanhMucSoDoPhong.add(new DanhMucSoDoPhong("T2P3", panelT2P3, lblT2P3, lblLoaiT2P3, lblTrangThaiT2P3));
        listDanhMucSoDoPhong.add(new DanhMucSoDoPhong("T2P4", panelT2P4, lblT2P4, lblLoaiT2P4, lblTrangThaiT2P4));
        listDanhMucSoDoPhong.add(new DanhMucSoDoPhong("T2P5", panelT2P5, lblT2P5, lblLoaiT2P5, lblTrangThaiT2P5));
        listDanhMucSoDoPhong.add(new DanhMucSoDoPhong("T3P1", panelT3P1, lblT3P1, lblLoaiT3P1, lblTrangThaiT3P1));
        listDanhMucSoDoPhong.add(new DanhMucSoDoPhong("T3P2", panelT3P2, lblT3P2, lblLoaiT3P2, lblTrangThaiT3P2));
        listDanhMucSoDoPhong.add(new DanhMucSoDoPhong("T3P3", panelT3P3, lblT3P3, lblLoaiT3P3, lblTrangThaiT3P3));
        listDanhMucSoDoPhong.add(new DanhMucSoDoPhong("T3P4", panelT3P4, lblT3P4, lblLoaiT3P4, lblTrangThaiT3P4));
        listDanhMucSoDoPhong.add(new DanhMucSoDoPhong("T3P5", panelT3P5, lblT3P5, lblLoaiT3P5, lblTrangThaiT3P5));
        listDanhMucSoDoPhong.add(new DanhMucSoDoPhong("T4P1", panelT4P1, lblT4P1, lblLoaiT4P1, lblTrangThaiT4P1));
        listDanhMucSoDoPhong.add(new DanhMucSoDoPhong("T4P2", panelT4P2, lblT4P2, lblLoaiT4P2, lblTrangThaiT4P2));
        listDanhMucSoDoPhong.add(new DanhMucSoDoPhong("T4P3", panelT4P3, lblT4P3, lblLoaiT4P3, lblTrangThaiT4P3));
        listDanhMucSoDoPhong.add(new DanhMucSoDoPhong("T4P4", panelT4P4, lblT4P4, lblLoaiT4P4, lblTrangThaiT4P4));
        listDanhMucSoDoPhong.add(new DanhMucSoDoPhong("T4P5", panelT4P5, lblT4P5, lblLoaiT4P5, lblTrangThaiT4P5));
        listDanhMucSoDoPhong.add(new DanhMucSoDoPhong("T5P1", panelT5P1, lblT5P1, lblLoaiT5P1, lblTrangThaiT5P1));
        listDanhMucSoDoPhong.add(new DanhMucSoDoPhong("T5P2", panelT5P2, lblT5P2, lblLoaiT5P2, lblTrangThaiT5P2));
        listDanhMucSoDoPhong.add(new DanhMucSoDoPhong("T5P3", panelT5P3, lblT5P3, lblLoaiT5P3, lblTrangThaiT5P3));
        listDanhMucSoDoPhong.add(new DanhMucSoDoPhong("T5P4", panelT5P4, lblT5P4, lblLoaiT5P4, lblTrangThaiT5P4));
        listDanhMucSoDoPhong.add(new DanhMucSoDoPhong("T5P5", panelT5P5, lblT5P5, lblLoaiT5P5, lblTrangThaiT5P5));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelTang1 = new javax.swing.JPanel();
        panelTang = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        panelT1P1 = new javax.swing.JPanel();
        lblT1P1 = new javax.swing.JLabel();
        lblLoaiT1P1 = new javax.swing.JLabel();
        lblTrangThaiT1P1 = new javax.swing.JLabel();
        panelT1P2 = new javax.swing.JPanel();
        lblT1P2 = new javax.swing.JLabel();
        lblLoaiT1P2 = new javax.swing.JLabel();
        lblTrangThaiT1P2 = new javax.swing.JLabel();
        panelT1P3 = new javax.swing.JPanel();
        lblT1P3 = new javax.swing.JLabel();
        lblLoaiT1P3 = new javax.swing.JLabel();
        lblTrangThaiT1P3 = new javax.swing.JLabel();
        panelT1P4 = new javax.swing.JPanel();
        lblT1P4 = new javax.swing.JLabel();
        lblLoaiT1P4 = new javax.swing.JLabel();
        lblTrangThaiT1P4 = new javax.swing.JLabel();
        panelT1P5 = new javax.swing.JPanel();
        lblT1P5 = new javax.swing.JLabel();
        lblLoaiT1P5 = new javax.swing.JLabel();
        lblTrangThaiT1P5 = new javax.swing.JLabel();
        panelTang2 = new javax.swing.JPanel();
        panelTang3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        panelT2P1 = new javax.swing.JPanel();
        lblT2P1 = new javax.swing.JLabel();
        lblLoaiT2P1 = new javax.swing.JLabel();
        lblTrangThaiT2P1 = new javax.swing.JLabel();
        panelT2P2 = new javax.swing.JPanel();
        lblT2P2 = new javax.swing.JLabel();
        lblLoaiT2P2 = new javax.swing.JLabel();
        lblTrangThaiT2P2 = new javax.swing.JLabel();
        panelT2P3 = new javax.swing.JPanel();
        lblT2P3 = new javax.swing.JLabel();
        lblLoaiT2P3 = new javax.swing.JLabel();
        lblTrangThaiT2P3 = new javax.swing.JLabel();
        panelT2P4 = new javax.swing.JPanel();
        lblT2P4 = new javax.swing.JLabel();
        lblLoaiT2P4 = new javax.swing.JLabel();
        lblTrangThaiT2P4 = new javax.swing.JLabel();
        panelT2P5 = new javax.swing.JPanel();
        lblT2P5 = new javax.swing.JLabel();
        lblLoaiT2P5 = new javax.swing.JLabel();
        lblTrangThaiT2P5 = new javax.swing.JLabel();
        panelTang4 = new javax.swing.JPanel();
        panelTang5 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        panelT3P1 = new javax.swing.JPanel();
        lblT3P1 = new javax.swing.JLabel();
        lblLoaiT3P1 = new javax.swing.JLabel();
        lblTrangThaiT3P1 = new javax.swing.JLabel();
        panelT3P2 = new javax.swing.JPanel();
        lblT3P2 = new javax.swing.JLabel();
        lblLoaiT3P2 = new javax.swing.JLabel();
        lblTrangThaiT3P2 = new javax.swing.JLabel();
        panelT3P3 = new javax.swing.JPanel();
        lblT3P3 = new javax.swing.JLabel();
        lblLoaiT3P3 = new javax.swing.JLabel();
        lblTrangThaiT3P3 = new javax.swing.JLabel();
        panelT3P4 = new javax.swing.JPanel();
        lblT3P4 = new javax.swing.JLabel();
        lblLoaiT3P4 = new javax.swing.JLabel();
        lblTrangThaiT3P4 = new javax.swing.JLabel();
        panelT3P5 = new javax.swing.JPanel();
        lblT3P5 = new javax.swing.JLabel();
        lblLoaiT3P5 = new javax.swing.JLabel();
        lblTrangThaiT3P5 = new javax.swing.JLabel();
        panelTang6 = new javax.swing.JPanel();
        panelTang7 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        panelT4P1 = new javax.swing.JPanel();
        lblT4P1 = new javax.swing.JLabel();
        lblLoaiT4P1 = new javax.swing.JLabel();
        lblTrangThaiT4P1 = new javax.swing.JLabel();
        panelT4P2 = new javax.swing.JPanel();
        lblT4P2 = new javax.swing.JLabel();
        lblLoaiT4P2 = new javax.swing.JLabel();
        lblTrangThaiT4P2 = new javax.swing.JLabel();
        panelT4P3 = new javax.swing.JPanel();
        lblT4P3 = new javax.swing.JLabel();
        lblLoaiT4P3 = new javax.swing.JLabel();
        lblTrangThaiT4P3 = new javax.swing.JLabel();
        panelT4P4 = new javax.swing.JPanel();
        lblT4P4 = new javax.swing.JLabel();
        lblLoaiT4P4 = new javax.swing.JLabel();
        lblTrangThaiT4P4 = new javax.swing.JLabel();
        panelT4P5 = new javax.swing.JPanel();
        lblT4P5 = new javax.swing.JLabel();
        lblLoaiT4P5 = new javax.swing.JLabel();
        lblTrangThaiT4P5 = new javax.swing.JLabel();
        panelTang8 = new javax.swing.JPanel();
        panelTang9 = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        panelT5P1 = new javax.swing.JPanel();
        lblT5P1 = new javax.swing.JLabel();
        lblLoaiT5P1 = new javax.swing.JLabel();
        lblTrangThaiT5P1 = new javax.swing.JLabel();
        panelT5P2 = new javax.swing.JPanel();
        lblT5P2 = new javax.swing.JLabel();
        lblLoaiT5P2 = new javax.swing.JLabel();
        lblTrangThaiT5P2 = new javax.swing.JLabel();
        panelT5P3 = new javax.swing.JPanel();
        lblT5P3 = new javax.swing.JLabel();
        lblLoaiT5P3 = new javax.swing.JLabel();
        lblTrangThaiT5P3 = new javax.swing.JLabel();
        panelT5P4 = new javax.swing.JPanel();
        lblT5P4 = new javax.swing.JLabel();
        lblLoaiT5P4 = new javax.swing.JLabel();
        lblTrangThaiT5P4 = new javax.swing.JLabel();
        panelT5P5 = new javax.swing.JPanel();
        lblT5P5 = new javax.swing.JLabel();
        lblLoaiT5P5 = new javax.swing.JLabel();
        lblTrangThaiT5P5 = new javax.swing.JLabel();

        panelTang1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelTang1.setLayout(new java.awt.GridLayout());

        panelTang.setBackground(new java.awt.Color(0, 153, 255));
        panelTang.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelTang.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Tầng 1");
        panelTang.add(jLabel2, new java.awt.GridBagConstraints());

        panelTang1.add(panelTang);

        panelT1P1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblT1P1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblT1P1.setForeground(new java.awt.Color(255, 255, 255));
        lblT1P1.setText("Số phòng");

        lblLoaiT1P1.setText("Loại:");

        lblTrangThaiT1P1.setText("Trạng thái:");

        javax.swing.GroupLayout panelT1P1Layout = new javax.swing.GroupLayout(panelT1P1);
        panelT1P1.setLayout(panelT1P1Layout);
        panelT1P1Layout.setHorizontalGroup(
            panelT1P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelT1P1Layout.createSequentialGroup()
                .addGroup(panelT1P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelT1P1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(lblT1P1))
                    .addGroup(panelT1P1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblLoaiT1P1))
                    .addGroup(panelT1P1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTrangThaiT1P1)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        panelT1P1Layout.setVerticalGroup(
            panelT1P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelT1P1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblT1P1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLoaiT1P1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTrangThaiT1P1)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        panelTang1.add(panelT1P1);

        panelT1P2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblT1P2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblT1P2.setForeground(new java.awt.Color(255, 255, 255));
        lblT1P2.setText("Số phòng");

        lblLoaiT1P2.setText("Loại:");

        lblTrangThaiT1P2.setText("Trạng thái:");

        javax.swing.GroupLayout panelT1P2Layout = new javax.swing.GroupLayout(panelT1P2);
        panelT1P2.setLayout(panelT1P2Layout);
        panelT1P2Layout.setHorizontalGroup(
            panelT1P2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelT1P2Layout.createSequentialGroup()
                .addGroup(panelT1P2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelT1P2Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(lblT1P2))
                    .addGroup(panelT1P2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblLoaiT1P2))
                    .addGroup(panelT1P2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTrangThaiT1P2)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        panelT1P2Layout.setVerticalGroup(
            panelT1P2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelT1P2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblT1P2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLoaiT1P2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTrangThaiT1P2)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        panelTang1.add(panelT1P2);

        panelT1P3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblT1P3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblT1P3.setForeground(new java.awt.Color(255, 255, 255));
        lblT1P3.setText("Số phòng");

        lblLoaiT1P3.setText("Loại:");

        lblTrangThaiT1P3.setText("Trạng thái:");

        javax.swing.GroupLayout panelT1P3Layout = new javax.swing.GroupLayout(panelT1P3);
        panelT1P3.setLayout(panelT1P3Layout);
        panelT1P3Layout.setHorizontalGroup(
            panelT1P3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelT1P3Layout.createSequentialGroup()
                .addGroup(panelT1P3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelT1P3Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(lblT1P3))
                    .addGroup(panelT1P3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblLoaiT1P3))
                    .addGroup(panelT1P3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTrangThaiT1P3)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        panelT1P3Layout.setVerticalGroup(
            panelT1P3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelT1P3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblT1P3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLoaiT1P3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTrangThaiT1P3)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        panelTang1.add(panelT1P3);

        panelT1P4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblT1P4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblT1P4.setForeground(new java.awt.Color(255, 255, 255));
        lblT1P4.setText("Số phòng");

        lblLoaiT1P4.setText("Loại:");

        lblTrangThaiT1P4.setText("Trạng thái:");

        javax.swing.GroupLayout panelT1P4Layout = new javax.swing.GroupLayout(panelT1P4);
        panelT1P4.setLayout(panelT1P4Layout);
        panelT1P4Layout.setHorizontalGroup(
            panelT1P4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelT1P4Layout.createSequentialGroup()
                .addGroup(panelT1P4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelT1P4Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(lblT1P4))
                    .addGroup(panelT1P4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblLoaiT1P4))
                    .addGroup(panelT1P4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTrangThaiT1P4)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        panelT1P4Layout.setVerticalGroup(
            panelT1P4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelT1P4Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblT1P4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLoaiT1P4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTrangThaiT1P4)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        panelTang1.add(panelT1P4);

        panelT1P5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblT1P5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblT1P5.setForeground(new java.awt.Color(255, 255, 255));
        lblT1P5.setText("Số phòng");

        lblLoaiT1P5.setText("Loại:");

        lblTrangThaiT1P5.setText("Trạng thái:");

        javax.swing.GroupLayout panelT1P5Layout = new javax.swing.GroupLayout(panelT1P5);
        panelT1P5.setLayout(panelT1P5Layout);
        panelT1P5Layout.setHorizontalGroup(
            panelT1P5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelT1P5Layout.createSequentialGroup()
                .addGroup(panelT1P5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelT1P5Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(lblT1P5))
                    .addGroup(panelT1P5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblLoaiT1P5))
                    .addGroup(panelT1P5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTrangThaiT1P5)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        panelT1P5Layout.setVerticalGroup(
            panelT1P5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelT1P5Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblT1P5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLoaiT1P5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTrangThaiT1P5)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        panelTang1.add(panelT1P5);

        panelTang2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelTang2.setLayout(new java.awt.GridLayout());

        panelTang3.setBackground(new java.awt.Color(0, 153, 255));
        panelTang3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelTang3.setLayout(new java.awt.GridBagLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Tầng 2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(40, 46, 44, 53);
        panelTang3.add(jLabel4, gridBagConstraints);

        panelTang2.add(panelTang3);

        panelT2P1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblT2P1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblT2P1.setForeground(new java.awt.Color(255, 255, 255));
        lblT2P1.setText("Số phòng");

        lblLoaiT2P1.setText("Loại:");

        lblTrangThaiT2P1.setText("Trạng thái:");

        javax.swing.GroupLayout panelT2P1Layout = new javax.swing.GroupLayout(panelT2P1);
        panelT2P1.setLayout(panelT2P1Layout);
        panelT2P1Layout.setHorizontalGroup(
            panelT2P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelT2P1Layout.createSequentialGroup()
                .addGroup(panelT2P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelT2P1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(lblT2P1))
                    .addGroup(panelT2P1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblLoaiT2P1))
                    .addGroup(panelT2P1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTrangThaiT2P1)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        panelT2P1Layout.setVerticalGroup(
            panelT2P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelT2P1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblT2P1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLoaiT2P1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTrangThaiT2P1)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        panelTang2.add(panelT2P1);

        panelT2P2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblT2P2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblT2P2.setForeground(new java.awt.Color(255, 255, 255));
        lblT2P2.setText("Số phòng");

        lblLoaiT2P2.setText("Loại:");

        lblTrangThaiT2P2.setText("Trạng thái:");

        javax.swing.GroupLayout panelT2P2Layout = new javax.swing.GroupLayout(panelT2P2);
        panelT2P2.setLayout(panelT2P2Layout);
        panelT2P2Layout.setHorizontalGroup(
            panelT2P2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelT2P2Layout.createSequentialGroup()
                .addGroup(panelT2P2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelT2P2Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(lblT2P2))
                    .addGroup(panelT2P2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblLoaiT2P2))
                    .addGroup(panelT2P2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTrangThaiT2P2)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        panelT2P2Layout.setVerticalGroup(
            panelT2P2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelT2P2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblT2P2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLoaiT2P2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTrangThaiT2P2)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        panelTang2.add(panelT2P2);

        panelT2P3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblT2P3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblT2P3.setForeground(new java.awt.Color(255, 255, 255));
        lblT2P3.setText("Số phòng");

        lblLoaiT2P3.setText("Loại:");

        lblTrangThaiT2P3.setText("Trạng thái:");

        javax.swing.GroupLayout panelT2P3Layout = new javax.swing.GroupLayout(panelT2P3);
        panelT2P3.setLayout(panelT2P3Layout);
        panelT2P3Layout.setHorizontalGroup(
            panelT2P3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelT2P3Layout.createSequentialGroup()
                .addGroup(panelT2P3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelT2P3Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(lblT2P3))
                    .addGroup(panelT2P3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblLoaiT2P3))
                    .addGroup(panelT2P3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTrangThaiT2P3)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        panelT2P3Layout.setVerticalGroup(
            panelT2P3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelT2P3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblT2P3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLoaiT2P3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTrangThaiT2P3)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        panelTang2.add(panelT2P3);

        panelT2P4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblT2P4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblT2P4.setForeground(new java.awt.Color(255, 255, 255));
        lblT2P4.setText("Số phòng");

        lblLoaiT2P4.setText("Loại:");

        lblTrangThaiT2P4.setText("Trạng thái:");

        javax.swing.GroupLayout panelT2P4Layout = new javax.swing.GroupLayout(panelT2P4);
        panelT2P4.setLayout(panelT2P4Layout);
        panelT2P4Layout.setHorizontalGroup(
            panelT2P4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelT2P4Layout.createSequentialGroup()
                .addGroup(panelT2P4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelT2P4Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(lblT2P4))
                    .addGroup(panelT2P4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblLoaiT2P4))
                    .addGroup(panelT2P4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTrangThaiT2P4)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        panelT2P4Layout.setVerticalGroup(
            panelT2P4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelT2P4Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblT2P4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLoaiT2P4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTrangThaiT2P4)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        panelTang2.add(panelT2P4);

        panelT2P5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblT2P5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblT2P5.setForeground(new java.awt.Color(255, 255, 255));
        lblT2P5.setText("Số phòng");

        lblLoaiT2P5.setText("Loại:");

        lblTrangThaiT2P5.setText("Trạng thái:");

        javax.swing.GroupLayout panelT2P5Layout = new javax.swing.GroupLayout(panelT2P5);
        panelT2P5.setLayout(panelT2P5Layout);
        panelT2P5Layout.setHorizontalGroup(
            panelT2P5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelT2P5Layout.createSequentialGroup()
                .addGroup(panelT2P5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelT2P5Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(lblT2P5))
                    .addGroup(panelT2P5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblLoaiT2P5))
                    .addGroup(panelT2P5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTrangThaiT2P5)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        panelT2P5Layout.setVerticalGroup(
            panelT2P5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelT2P5Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblT2P5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLoaiT2P5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTrangThaiT2P5)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        panelTang2.add(panelT2P5);

        panelTang4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelTang4.setLayout(new java.awt.GridLayout());

        panelTang5.setBackground(new java.awt.Color(0, 153, 255));
        panelTang5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelTang5.setLayout(new java.awt.GridBagLayout());

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel23.setText("Tầng 3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(45, 44, 39, 55);
        panelTang5.add(jLabel23, gridBagConstraints);

        panelTang4.add(panelTang5);

        panelT3P1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblT3P1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblT3P1.setForeground(new java.awt.Color(255, 255, 255));
        lblT3P1.setText("Số phòng");

        lblLoaiT3P1.setText("Loại:");

        lblTrangThaiT3P1.setText("Trạng thái:");

        javax.swing.GroupLayout panelT3P1Layout = new javax.swing.GroupLayout(panelT3P1);
        panelT3P1.setLayout(panelT3P1Layout);
        panelT3P1Layout.setHorizontalGroup(
            panelT3P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelT3P1Layout.createSequentialGroup()
                .addGroup(panelT3P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelT3P1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(lblT3P1))
                    .addGroup(panelT3P1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblLoaiT3P1))
                    .addGroup(panelT3P1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTrangThaiT3P1)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        panelT3P1Layout.setVerticalGroup(
            panelT3P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelT3P1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblT3P1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLoaiT3P1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTrangThaiT3P1)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        panelTang4.add(panelT3P1);

        panelT3P2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblT3P2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblT3P2.setForeground(new java.awt.Color(255, 255, 255));
        lblT3P2.setText("Số phòng");

        lblLoaiT3P2.setText("Loại:");

        lblTrangThaiT3P2.setText("Trạng thái:");

        javax.swing.GroupLayout panelT3P2Layout = new javax.swing.GroupLayout(panelT3P2);
        panelT3P2.setLayout(panelT3P2Layout);
        panelT3P2Layout.setHorizontalGroup(
            panelT3P2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelT3P2Layout.createSequentialGroup()
                .addGroup(panelT3P2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelT3P2Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(lblT3P2))
                    .addGroup(panelT3P2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblLoaiT3P2))
                    .addGroup(panelT3P2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTrangThaiT3P2)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        panelT3P2Layout.setVerticalGroup(
            panelT3P2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelT3P2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblT3P2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLoaiT3P2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTrangThaiT3P2)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        panelTang4.add(panelT3P2);

        panelT3P3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblT3P3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblT3P3.setForeground(new java.awt.Color(255, 255, 255));
        lblT3P3.setText("Số phòng");

        lblLoaiT3P3.setText("Loại:");

        lblTrangThaiT3P3.setText("Trạng thái:");

        javax.swing.GroupLayout panelT3P3Layout = new javax.swing.GroupLayout(panelT3P3);
        panelT3P3.setLayout(panelT3P3Layout);
        panelT3P3Layout.setHorizontalGroup(
            panelT3P3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelT3P3Layout.createSequentialGroup()
                .addGroup(panelT3P3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelT3P3Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(lblT3P3))
                    .addGroup(panelT3P3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblLoaiT3P3))
                    .addGroup(panelT3P3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTrangThaiT3P3)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        panelT3P3Layout.setVerticalGroup(
            panelT3P3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelT3P3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblT3P3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLoaiT3P3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTrangThaiT3P3)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        panelTang4.add(panelT3P3);

        panelT3P4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblT3P4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblT3P4.setForeground(new java.awt.Color(255, 255, 255));
        lblT3P4.setText("Số phòng");

        lblLoaiT3P4.setText("Loại:");

        lblTrangThaiT3P4.setText("Trạng thái:");

        javax.swing.GroupLayout panelT3P4Layout = new javax.swing.GroupLayout(panelT3P4);
        panelT3P4.setLayout(panelT3P4Layout);
        panelT3P4Layout.setHorizontalGroup(
            panelT3P4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelT3P4Layout.createSequentialGroup()
                .addGroup(panelT3P4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelT3P4Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(lblT3P4))
                    .addGroup(panelT3P4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblLoaiT3P4))
                    .addGroup(panelT3P4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTrangThaiT3P4)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        panelT3P4Layout.setVerticalGroup(
            panelT3P4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelT3P4Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblT3P4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLoaiT3P4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTrangThaiT3P4)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        panelTang4.add(panelT3P4);

        panelT3P5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblT3P5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblT3P5.setForeground(new java.awt.Color(255, 255, 255));
        lblT3P5.setText("Số phòng");

        lblLoaiT3P5.setText("Loại:");

        lblTrangThaiT3P5.setText("Trạng thái:");

        javax.swing.GroupLayout panelT3P5Layout = new javax.swing.GroupLayout(panelT3P5);
        panelT3P5.setLayout(panelT3P5Layout);
        panelT3P5Layout.setHorizontalGroup(
            panelT3P5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelT3P5Layout.createSequentialGroup()
                .addGroup(panelT3P5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelT3P5Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(lblT3P5))
                    .addGroup(panelT3P5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblLoaiT3P5))
                    .addGroup(panelT3P5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTrangThaiT3P5)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        panelT3P5Layout.setVerticalGroup(
            panelT3P5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelT3P5Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblT3P5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLoaiT3P5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTrangThaiT3P5)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        panelTang4.add(panelT3P5);

        panelTang6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelTang6.setLayout(new java.awt.GridLayout());

        panelTang7.setBackground(new java.awt.Color(0, 153, 255));
        panelTang7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelTang7.setLayout(new java.awt.GridBagLayout());

        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel34.setText("Tầng 4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(43, 45, 41, 54);
        panelTang7.add(jLabel34, gridBagConstraints);

        panelTang6.add(panelTang7);

        panelT4P1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblT4P1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblT4P1.setForeground(new java.awt.Color(255, 255, 255));
        lblT4P1.setText("Số phòng");

        lblLoaiT4P1.setText("Loại:");

        lblTrangThaiT4P1.setText("Trạng thái:");

        javax.swing.GroupLayout panelT4P1Layout = new javax.swing.GroupLayout(panelT4P1);
        panelT4P1.setLayout(panelT4P1Layout);
        panelT4P1Layout.setHorizontalGroup(
            panelT4P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelT4P1Layout.createSequentialGroup()
                .addGroup(panelT4P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelT4P1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(lblT4P1))
                    .addGroup(panelT4P1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblLoaiT4P1))
                    .addGroup(panelT4P1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTrangThaiT4P1)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        panelT4P1Layout.setVerticalGroup(
            panelT4P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelT4P1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblT4P1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLoaiT4P1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTrangThaiT4P1)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        panelTang6.add(panelT4P1);

        panelT4P2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblT4P2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblT4P2.setForeground(new java.awt.Color(255, 255, 255));
        lblT4P2.setText("Số phòng");

        lblLoaiT4P2.setText("Loại:");

        lblTrangThaiT4P2.setText("Trạng thái:");

        javax.swing.GroupLayout panelT4P2Layout = new javax.swing.GroupLayout(panelT4P2);
        panelT4P2.setLayout(panelT4P2Layout);
        panelT4P2Layout.setHorizontalGroup(
            panelT4P2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelT4P2Layout.createSequentialGroup()
                .addGroup(panelT4P2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelT4P2Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(lblT4P2))
                    .addGroup(panelT4P2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblLoaiT4P2))
                    .addGroup(panelT4P2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTrangThaiT4P2)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        panelT4P2Layout.setVerticalGroup(
            panelT4P2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelT4P2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblT4P2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLoaiT4P2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTrangThaiT4P2)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        panelTang6.add(panelT4P2);

        panelT4P3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblT4P3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblT4P3.setForeground(new java.awt.Color(255, 255, 255));
        lblT4P3.setText("Số phòng");

        lblLoaiT4P3.setText("Loại:");

        lblTrangThaiT4P3.setText("Trạng thái:");

        javax.swing.GroupLayout panelT4P3Layout = new javax.swing.GroupLayout(panelT4P3);
        panelT4P3.setLayout(panelT4P3Layout);
        panelT4P3Layout.setHorizontalGroup(
            panelT4P3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelT4P3Layout.createSequentialGroup()
                .addGroup(panelT4P3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelT4P3Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(lblT4P3))
                    .addGroup(panelT4P3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblLoaiT4P3))
                    .addGroup(panelT4P3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTrangThaiT4P3)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        panelT4P3Layout.setVerticalGroup(
            panelT4P3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelT4P3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblT4P3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLoaiT4P3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTrangThaiT4P3)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        panelTang6.add(panelT4P3);

        panelT4P4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblT4P4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblT4P4.setForeground(new java.awt.Color(255, 255, 255));
        lblT4P4.setText("Số phòng");

        lblLoaiT4P4.setText("Loại:");

        lblTrangThaiT4P4.setText("Trạng thái:");

        javax.swing.GroupLayout panelT4P4Layout = new javax.swing.GroupLayout(panelT4P4);
        panelT4P4.setLayout(panelT4P4Layout);
        panelT4P4Layout.setHorizontalGroup(
            panelT4P4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelT4P4Layout.createSequentialGroup()
                .addGroup(panelT4P4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelT4P4Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(lblT4P4))
                    .addGroup(panelT4P4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblLoaiT4P4))
                    .addGroup(panelT4P4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTrangThaiT4P4)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        panelT4P4Layout.setVerticalGroup(
            panelT4P4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelT4P4Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblT4P4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLoaiT4P4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTrangThaiT4P4)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        panelTang6.add(panelT4P4);

        panelT4P5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblT4P5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblT4P5.setForeground(new java.awt.Color(255, 255, 255));
        lblT4P5.setText("Số phòng");

        lblLoaiT4P5.setText("Loại:");

        lblTrangThaiT4P5.setText("Trạng thái:");

        javax.swing.GroupLayout panelT4P5Layout = new javax.swing.GroupLayout(panelT4P5);
        panelT4P5.setLayout(panelT4P5Layout);
        panelT4P5Layout.setHorizontalGroup(
            panelT4P5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelT4P5Layout.createSequentialGroup()
                .addGroup(panelT4P5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelT4P5Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(lblT4P5))
                    .addGroup(panelT4P5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblLoaiT4P5))
                    .addGroup(panelT4P5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTrangThaiT4P5)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        panelT4P5Layout.setVerticalGroup(
            panelT4P5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelT4P5Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblT4P5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLoaiT4P5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTrangThaiT4P5)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        panelTang6.add(panelT4P5);

        panelTang8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelTang8.setLayout(new java.awt.GridLayout());

        panelTang9.setBackground(new java.awt.Color(0, 153, 255));
        panelTang9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelTang9.setLayout(new java.awt.GridBagLayout());

        jLabel45.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel45.setText("Tầng 5");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(41, 46, 43, 53);
        panelTang9.add(jLabel45, gridBagConstraints);

        panelTang8.add(panelTang9);

        panelT5P1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblT5P1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblT5P1.setForeground(new java.awt.Color(255, 255, 255));
        lblT5P1.setText("Số phòng");

        lblLoaiT5P1.setText("Loại:");

        lblTrangThaiT5P1.setText("Trạng thái:");

        javax.swing.GroupLayout panelT5P1Layout = new javax.swing.GroupLayout(panelT5P1);
        panelT5P1.setLayout(panelT5P1Layout);
        panelT5P1Layout.setHorizontalGroup(
            panelT5P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelT5P1Layout.createSequentialGroup()
                .addGroup(panelT5P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelT5P1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(lblT5P1))
                    .addGroup(panelT5P1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblLoaiT5P1))
                    .addGroup(panelT5P1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTrangThaiT5P1)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        panelT5P1Layout.setVerticalGroup(
            panelT5P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelT5P1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblT5P1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLoaiT5P1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTrangThaiT5P1)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        panelTang8.add(panelT5P1);

        panelT5P2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblT5P2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblT5P2.setForeground(new java.awt.Color(255, 255, 255));
        lblT5P2.setText("Số phòng");

        lblLoaiT5P2.setText("Loại:");

        lblTrangThaiT5P2.setText("Trạng thái:");

        javax.swing.GroupLayout panelT5P2Layout = new javax.swing.GroupLayout(panelT5P2);
        panelT5P2.setLayout(panelT5P2Layout);
        panelT5P2Layout.setHorizontalGroup(
            panelT5P2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelT5P2Layout.createSequentialGroup()
                .addGroup(panelT5P2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelT5P2Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(lblT5P2))
                    .addGroup(panelT5P2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblLoaiT5P2))
                    .addGroup(panelT5P2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTrangThaiT5P2)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        panelT5P2Layout.setVerticalGroup(
            panelT5P2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelT5P2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblT5P2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLoaiT5P2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTrangThaiT5P2)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        panelTang8.add(panelT5P2);

        panelT5P3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblT5P3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblT5P3.setForeground(new java.awt.Color(255, 255, 255));
        lblT5P3.setText("Số phòng");

        lblLoaiT5P3.setText("Loại:");

        lblTrangThaiT5P3.setText("Trạng thái:");

        javax.swing.GroupLayout panelT5P3Layout = new javax.swing.GroupLayout(panelT5P3);
        panelT5P3.setLayout(panelT5P3Layout);
        panelT5P3Layout.setHorizontalGroup(
            panelT5P3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelT5P3Layout.createSequentialGroup()
                .addGroup(panelT5P3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelT5P3Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(lblT5P3))
                    .addGroup(panelT5P3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblLoaiT5P3))
                    .addGroup(panelT5P3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTrangThaiT5P3)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        panelT5P3Layout.setVerticalGroup(
            panelT5P3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelT5P3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblT5P3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLoaiT5P3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTrangThaiT5P3)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        panelTang8.add(panelT5P3);

        panelT5P4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblT5P4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblT5P4.setForeground(new java.awt.Color(255, 255, 255));
        lblT5P4.setText("Số phòng");

        lblLoaiT5P4.setText("Loại:");

        lblTrangThaiT5P4.setText("Trạng thái:");

        javax.swing.GroupLayout panelT5P4Layout = new javax.swing.GroupLayout(panelT5P4);
        panelT5P4.setLayout(panelT5P4Layout);
        panelT5P4Layout.setHorizontalGroup(
            panelT5P4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelT5P4Layout.createSequentialGroup()
                .addGroup(panelT5P4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelT5P4Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(lblT5P4))
                    .addGroup(panelT5P4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblLoaiT5P4))
                    .addGroup(panelT5P4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTrangThaiT5P4)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        panelT5P4Layout.setVerticalGroup(
            panelT5P4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelT5P4Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblT5P4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLoaiT5P4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTrangThaiT5P4)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        panelTang8.add(panelT5P4);

        panelT5P5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblT5P5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblT5P5.setForeground(new java.awt.Color(255, 255, 255));
        lblT5P5.setText("Số phòng");

        lblLoaiT5P5.setText("Loại:");

        lblTrangThaiT5P5.setText("Trạng thái:");

        javax.swing.GroupLayout panelT5P5Layout = new javax.swing.GroupLayout(panelT5P5);
        panelT5P5.setLayout(panelT5P5Layout);
        panelT5P5Layout.setHorizontalGroup(
            panelT5P5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelT5P5Layout.createSequentialGroup()
                .addGroup(panelT5P5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelT5P5Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(lblT5P5))
                    .addGroup(panelT5P5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblLoaiT5P5))
                    .addGroup(panelT5P5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTrangThaiT5P5)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        panelT5P5Layout.setVerticalGroup(
            panelT5P5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelT5P5Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblT5P5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLoaiT5P5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTrangThaiT5P5)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        panelTang8.add(panelT5P5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTang1, javax.swing.GroupLayout.PREFERRED_SIZE, 874, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(panelTang2, javax.swing.GroupLayout.PREFERRED_SIZE, 874, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(panelTang4, javax.swing.GroupLayout.PREFERRED_SIZE, 874, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(panelTang6, javax.swing.GroupLayout.PREFERRED_SIZE, 874, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(panelTang8, javax.swing.GroupLayout.PREFERRED_SIZE, 874, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelTang1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelTang2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelTang4, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelTang6, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelTang8, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel lblLoaiT1P1;
    private javax.swing.JLabel lblLoaiT1P2;
    private javax.swing.JLabel lblLoaiT1P3;
    private javax.swing.JLabel lblLoaiT1P4;
    private javax.swing.JLabel lblLoaiT1P5;
    private javax.swing.JLabel lblLoaiT2P1;
    private javax.swing.JLabel lblLoaiT2P2;
    private javax.swing.JLabel lblLoaiT2P3;
    private javax.swing.JLabel lblLoaiT2P4;
    private javax.swing.JLabel lblLoaiT2P5;
    private javax.swing.JLabel lblLoaiT3P1;
    private javax.swing.JLabel lblLoaiT3P2;
    private javax.swing.JLabel lblLoaiT3P3;
    private javax.swing.JLabel lblLoaiT3P4;
    private javax.swing.JLabel lblLoaiT3P5;
    private javax.swing.JLabel lblLoaiT4P1;
    private javax.swing.JLabel lblLoaiT4P2;
    private javax.swing.JLabel lblLoaiT4P3;
    private javax.swing.JLabel lblLoaiT4P4;
    private javax.swing.JLabel lblLoaiT4P5;
    private javax.swing.JLabel lblLoaiT5P1;
    private javax.swing.JLabel lblLoaiT5P2;
    private javax.swing.JLabel lblLoaiT5P3;
    private javax.swing.JLabel lblLoaiT5P4;
    private javax.swing.JLabel lblLoaiT5P5;
    private javax.swing.JLabel lblT1P1;
    private javax.swing.JLabel lblT1P2;
    private javax.swing.JLabel lblT1P3;
    private javax.swing.JLabel lblT1P4;
    private javax.swing.JLabel lblT1P5;
    private javax.swing.JLabel lblT2P1;
    private javax.swing.JLabel lblT2P2;
    private javax.swing.JLabel lblT2P3;
    private javax.swing.JLabel lblT2P4;
    private javax.swing.JLabel lblT2P5;
    private javax.swing.JLabel lblT3P1;
    private javax.swing.JLabel lblT3P2;
    private javax.swing.JLabel lblT3P3;
    private javax.swing.JLabel lblT3P4;
    private javax.swing.JLabel lblT3P5;
    private javax.swing.JLabel lblT4P1;
    private javax.swing.JLabel lblT4P2;
    private javax.swing.JLabel lblT4P3;
    private javax.swing.JLabel lblT4P4;
    private javax.swing.JLabel lblT4P5;
    private javax.swing.JLabel lblT5P1;
    private javax.swing.JLabel lblT5P2;
    private javax.swing.JLabel lblT5P3;
    private javax.swing.JLabel lblT5P4;
    private javax.swing.JLabel lblT5P5;
    private javax.swing.JLabel lblTrangThaiT1P1;
    private javax.swing.JLabel lblTrangThaiT1P2;
    private javax.swing.JLabel lblTrangThaiT1P3;
    private javax.swing.JLabel lblTrangThaiT1P4;
    private javax.swing.JLabel lblTrangThaiT1P5;
    private javax.swing.JLabel lblTrangThaiT2P1;
    private javax.swing.JLabel lblTrangThaiT2P2;
    private javax.swing.JLabel lblTrangThaiT2P3;
    private javax.swing.JLabel lblTrangThaiT2P4;
    private javax.swing.JLabel lblTrangThaiT2P5;
    private javax.swing.JLabel lblTrangThaiT3P1;
    private javax.swing.JLabel lblTrangThaiT3P2;
    private javax.swing.JLabel lblTrangThaiT3P3;
    private javax.swing.JLabel lblTrangThaiT3P4;
    private javax.swing.JLabel lblTrangThaiT3P5;
    private javax.swing.JLabel lblTrangThaiT4P1;
    private javax.swing.JLabel lblTrangThaiT4P2;
    private javax.swing.JLabel lblTrangThaiT4P3;
    private javax.swing.JLabel lblTrangThaiT4P4;
    private javax.swing.JLabel lblTrangThaiT4P5;
    private javax.swing.JLabel lblTrangThaiT5P1;
    private javax.swing.JLabel lblTrangThaiT5P2;
    private javax.swing.JLabel lblTrangThaiT5P3;
    private javax.swing.JLabel lblTrangThaiT5P4;
    private javax.swing.JLabel lblTrangThaiT5P5;
    private javax.swing.JPanel panelT1P1;
    private javax.swing.JPanel panelT1P2;
    private javax.swing.JPanel panelT1P3;
    private javax.swing.JPanel panelT1P4;
    private javax.swing.JPanel panelT1P5;
    private javax.swing.JPanel panelT2P1;
    private javax.swing.JPanel panelT2P2;
    private javax.swing.JPanel panelT2P3;
    private javax.swing.JPanel panelT2P4;
    private javax.swing.JPanel panelT2P5;
    private javax.swing.JPanel panelT3P1;
    private javax.swing.JPanel panelT3P2;
    private javax.swing.JPanel panelT3P3;
    private javax.swing.JPanel panelT3P4;
    private javax.swing.JPanel panelT3P5;
    private javax.swing.JPanel panelT4P1;
    private javax.swing.JPanel panelT4P2;
    private javax.swing.JPanel panelT4P3;
    private javax.swing.JPanel panelT4P4;
    private javax.swing.JPanel panelT4P5;
    private javax.swing.JPanel panelT5P1;
    private javax.swing.JPanel panelT5P2;
    private javax.swing.JPanel panelT5P3;
    private javax.swing.JPanel panelT5P4;
    private javax.swing.JPanel panelT5P5;
    private javax.swing.JPanel panelTang;
    private javax.swing.JPanel panelTang1;
    private javax.swing.JPanel panelTang2;
    private javax.swing.JPanel panelTang3;
    private javax.swing.JPanel panelTang4;
    private javax.swing.JPanel panelTang5;
    private javax.swing.JPanel panelTang6;
    private javax.swing.JPanel panelTang7;
    private javax.swing.JPanel panelTang8;
    private javax.swing.JPanel panelTang9;
    // End of variables declaration//GEN-END:variables
}
